# Generated by Django 4.1 on 2022-09-26 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], message='file必須為jpg或png檔案')]),
        ),
    ]
