# Generated by Django 4.1 on 2022-09-27 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0003_video_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], message='file必須為jpg或png檔案')]),
        ),
    ]
