# Generated by Django 4.1 on 2022-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name=''),
        ),
    ]
