# Generated by Django 4.1 on 2022-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0007_rename_name_photo_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(blank=True, default='image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, default='video', max_length=500, null=True),
        ),
    ]
