# Generated by Django 4.1 on 2022-09-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0008_alter_photo_type_alter_video_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='image',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
