# Generated by Django 4.1 on 2022-10-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0010_alter_photo_upload_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
