# Generated by Django 4.1 on 2022-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0011_rename_image_photo_file_rename_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='media_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='media_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
