# Generated by Django 4.1 on 2022-10-04 08:44

from django.db import migrations
import media_page.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0012_photo_media_filename_video_media_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AlterField(
            model_name='photo',
            name='media_filename',
            field=media_page.fields.RestrictedFileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_filename',
            field=media_page.fields.RestrictedFileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
