# Generated by Django 4.1 on 2022-10-04 11:28

from django.db import migrations, models
import media_page.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0013_remove_photo_file_remove_photo_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=media_page.fields.RestrictedFileField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=media_page.fields.RestrictedFileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='media_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
