# Generated by Django 4.1 on 2022-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_page', '0014_photo_file_video_file_alter_photo_media_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(blank=True, default=['image/jpg', 'image/png'], max_length=500, null=True),
        ),
    ]
